FIND_PATH(CASACORE_INCLUDE_DIR casacore/casa/Arrays.h PATHS /opt/share/casa/current/release/include)
FIND_LIBRARY(CASACORE_LIBRARY NAMES casacore PATHS /opt/share/casa/current/release/lib64)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CASACORE DEFAULT_MSG CASACORE_LIBRARY CASACORE_INCLUDE_DIR)

IF(CASACORE_FOUND)
  SET(CASACORE_LIBRARIES ${CASACORE_LIBRARY})
  get_filename_component(CASACORE_LIBRARY_PATH "${CASACORE_LIBRARY}" PATH)
  SET(CASACORE_EXE_LINKER_FLAGS "-L ${CASACORE_LIBRARY_PATH} -Wl,-rpath,${CASACORE_LIBRARY_PATH} -lcasacore")
ELSE(CASACORE_FOUND)
  SET(CASACORE_LIBRARIES)
ENDIF(CASACORE_FOUND)

MARK_AS_ADVANCED(CASACORE_INCLUDE_DIR CASACORE_LIBRARIES)
